[package]
name = "cache_control"
version = "0.1.0"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.91", features = ["derive"] }
regex = "1.1.6"
