[package]
name = "site"
version = "0.0.1"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
chrono = { version = "0.4.6", features = ["serde"] }
common = { path = "../common" }
fallible-iterator = "0.2.0"
hyper = "0.12.29"
lazy_static = "1.3.0"
multipart = { version = "0.16.1", default-features = false, features = ["server"] }
postgres = { version = "0.16.0-rc.1", features = ["with-chrono-0_4"] }
r2d2_postgres = "0.15.0-rc.1"
regex = "1.1.6"
serde = { version = "1.0.92", features = ["derive"] }
tera = "1.0.0-beta.7"
url = "1.7.2"
warp = "0.1.15"

[build-dependencies]
askama = "0.8.0"
