[package]
name = "site"
version = "0.0.1"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
common = { path = "../common" }
fallible-iterator = "0.2.0"
hyper = "0.12.29"
lazy_static = "1.3.0"
multipart = { version = "0.16.1", default-features = false, features = ["server"] }
regex = "1.1.6"
serde = { version = "1.0.92", features = ["derive"] }
tera = "1.0.0-beta.7"
url = "1.7.2"
gotham = "0.4.0"
mime = "0.3.13"
gotham_derive = "0.4.0"
futures = "0.1.28"
log = "0.4.8"
