[package]
name = "site"
version = "0.1.0"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"

[dependencies]
gotham = "*"
askama = "*"
hyper = "*"
mime = "*"
tokio-postgres = "0.4.0-rc.2"

[build-dependencies]
askama = "*"
