[package]
name = "hasher"
version = "0.0.1"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
postgres = "0.16.0-rc.1"
fallible-iterator = "0.2"
futures = "0.1.28"
tokio = "0.1.22"
