[package]
name = "common"
version = "0.0.1"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"

[dependencies]
cache_control = { path = "../cache_control" }
chrono = "0.4.6"
failure = "0.1.5"
fern = "0.5.8"
lazy_static = "1.3.0"
log = "0.4.6"
r2d2_postgres = "0.15.0-rc.1"
regex = "1.1.6"
reqwest = "0.9.17"
serde = { version = "1.0.92", features = ["derive"] }
tokio-postgres = { version = "0.4.0-rc.2", features = ["with-chrono-0_4"] }
toml = "0.5.1"
url = "1.7.2"
scraper = "0.10.0"
image = "0.21.2"
tokio = "0.1.22"
macros = { path = "../macros" }
futures = "0.1.28"

[build-dependencies]
image = "0.21.2"
