[package]
name = "common"
version = "0.1.0"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"

[dependencies]
image = { git = "https://github.com/image-rs/image" }
tokio-postgres = {version = "0.4.0-rc.2", features = ["with-chrono-0_4"]}
url = "^1.7.2"
futures = "*"
log = "^0.4.6"
fern = "*"
failure = "*"
regex = "*"
serde = {version = "*", features = ["derive"]}
r2d2_postgres = "0.15.0-rc.1"
chrono = "*"
lazy_static = "*"
reqwest = "*"
toml = "*"
cache_control = {path = "../cache_control"}
phf = "*"
serde_json = "^1.0.39"

[build-dependencies]
phf = "*"
phf_codegen = "*"
image = { git = "https://github.com/image-rs/image" }
