[package]
name = "common"
version = "0.0.1"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"

[dependencies]
cache_control = {path = "../cache_control"}
chrono = "0.4.6"
failure = "0.1.5"
fern = "0.5.8"
image = { git = "https://github.com/image-rs/image" }
lazy_static = "1.3.0"
log = "0.4.6"
phf = "0.7.24"
r2d2_postgres = "0.15.0-rc.1"
regex = "1.1.6"
reqwest = "0.9.17"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
tokio-postgres = { version = "0.4.0-rc.2", features = ["with-chrono-0_4"] }
toml = "0.5.1"
url = "1.7.2"

[build-dependencies]
image = { git = "https://github.com/image-rs/image" }
phf = "0.7.24"
phf_codegen = "0.7.24"
