[package]
name = "common"
version = "0.0.1"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"

[dependencies]
cache_control = { path = "../cache_control" }
chrono = { version = "0.4.7", features = ["serde"] }
failure = "0.1.5"
fern = "0.5.8"
lazy_static = "1.3.0"
log = "0.4.6"
regex = "1.1.6"
serde = { version = "1.0.92", features = ["derive"] }
tokio-postgres = { version = "0.4.0-rc.3", features = ["with-chrono-0_4"] }
toml = "0.5.1"
url = "1.7.2"
image = "0.22.2"
tokio = "0.1.22"
macros = { path = "../macros" }
futures = "0.1.28"
serde_json = "1.0.40"

[dependencies.reqwest]
version = "0.9.19"
default-features = false
features = ["rustls-tls"]
