[package]
name = "common"
version = "0.1.0"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"

[dependencies]
image = "*"
tokio-postgres = "0.4.0-rc.2"
url = "*"
hyper = "*"
http = "*"
futures = "*"
log = "*"
fern = "*"
failure = "*"
regex = "*"
