[package]
name = "ingest"
version = "0.0.1"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"
description = "Tool for automatically ingesting PushShift downloads"

[dependencies]
zstd = "0.4.24"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"
clap = "2.33.0"
common = { path = "../common" }
lazy_static = "1.3.0"
tokio-postgres = { version = "0.4.0-rc.3", features = ["with-chrono-0_4"] }
log = "0.4.6"
bzip2 = "0.3.3"
xz2 = "0.1.6"
regex = "1.1.6"
failure = "0.1.5"
hyper = "0.12.31"
tokio = "0.1.22"
macros = { path = "../macros" }
futures = "0.1.28"
url = "1.7.2"
tokio-executor = "0.1.8"
chrono = { version = "0.4.7", features = ["serde"] }

[dependencies.reqwest]
version = "0.9.19"
default-features = false
features = ["rustls-tls"]
