[package]
name = "ingest"
version = "0.0.1"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"
description = "Tool for automatically ingesting PushShift downloads"

[dependencies]
zstd = "0.4.24"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
reqwest = "0.9.17"
postgres = { version = "0.16.0-rc.1", features = ["with-chrono-0_4"] }
clap = "2.33.0"
common = {path = "../common"}
lazy_static = "1.3.0"
r2d2_postgres = "0.15.0-rc.1"
log = "0.4.6"
rayon = "1.0.3"
fallible-iterator = "0.2.0"
bzip2 = "0.3.3"
xz2 = "0.1.6"
regex = "1.1.6"
failure = "0.1.5"
