[package]
name = "op"
version = "0.0.1"
authors = ["Elaina Martineau <elainamartineau@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
serde_json = "1.0.40"
serde = "1.0.98"
failure = "0.1.5"

[dependencies.reqwest]
version = "0.9.19"
default-features = false
features = ["rustls-tls"]
